### ISSUE TITLE
Insecure key exchange 

### ISSUE THREAD

**Issue by alepacheco** [SaturnsVoid/Windows-Backdoor-AES#1]
Your implementation of the key exchange is trivial and insecure, if the attacker can monitor the connection it won't matter if it is or not encrypted because the AES key is send in clear text.
You could try some more creative way to exchange the keys but the easier way is to use RSA,
I have left you some links if you want to look further.

If you are interested, this page in stackexchange is easy to read:
https://security.stackexchange.com/questions/45963/diffie-hellman-key-exchange-in-plain-english
https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange

If you are not happy with me commenting in your repos, please let me know.

**Comment by SaturnsVoid** [comment]
No, Its fine. Its good to learn. I was looking at using RSA but just was lazy and used AES. 

Yes the key should be encoded/encrypted.  I will take a look at your sources.

Thanks

**Comment by alepacheco** [comment]
Unfortunately I never added encryption in my projects but if you are interested we could make a simple tcp wrapper library that handles all the exchange, or maybe there are some out there.
